### ISSUE TITLE
Makefile:4424: recipe for target 'src/bison-scan-code-c.o' failed

### ISSUE THREAD

**Issue by ubuntu-repo** [akimd/bison#10]
I couldn't build bison due to a fatal error:
Makefile:4424: recipe for target 'src/bison-scan-code-c.o' failed.
The error is: src/scan-code-c.c:3:10: fatal error: src/scan-code.c: No such file or directory
 #include "src/scan-code.c"
There is a 'scan-code.l' and there is a 'scan-code-c.c' in the src directory, but no 'scan-code.c'.

-----------------------------------
Running make > ~/error.txt produces:
make[1]: Entering directory '/home/rob/Source/github/bison'
  LEX      examples/c/reccalc/scan.stamp
make[1]: Leaving directory '/home/rob/Source/github/bison'
make[1]: Entering directory '/home/rob/Source/github/bison'
  LEX      examples/c/reccalc/scan.stamp
make[1]: Leaving directory '/home/rob/Source/github/bison'
  LEX      src/scan-code.c
  LEX      src/scan-gram.c
  LEX      src/scan-skel.c
make  all-recursive
make[1]: Entering directory '/home/rob/Source/github/bison'
Making all in po
make[2]: Entering directory '/home/rob/Source/github/bison/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/rob/Source/github/bison/po'
Making all in runtime-po
make[2]: Entering directory '/home/rob/Source/github/bison/runtime-po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/rob/Source/github/bison/runtime-po'
Making all in gnulib-po
make[2]: Entering directory '/home/rob/Source/github/bison/gnulib-po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/rob/Source/github/bison/gnulib-po'
Making all in .
make[2]: Entering directory '/home/rob/Source/github/bison'
  CC       src/bison-scan-code-c.o
Makefile:4424: recipe for target 'src/bison-scan-code-c.o' failed
make[2]: Leaving directory '/home/rob/Source/github/bison'
Makefile:5371: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/home/rob/Source/github/bison'
Makefile:2940: recipe for target 'all' failed

**Comment by akimd** [comment]
Hi,
Did you start from the repo, or from a released tarball?
Sorry, I had not seen your message earlier.

**Comment by akimd** [comment]
No answer, closing.

**Comment by x-yuri** [comment]
I started from the repo, and the following [patch][a] helped me.

[a]: https://lists.gnu.org/archive/html/bison-patches/2014-12/msg00000.html
