### ISSUE TITLE
Inconsistent use of static_cast in c++ skeleton (lalr1.cc)

### ISSUE THREAD

**Issue by donmac703** [akimd/bison#20]
Line 924 reads:
yypush_ ("Shifting", static_cast<state_type> (yyn), YY_MOVE (yyla));]b4_lac_if([[

Line 855 does not use static_cast:
YYCDEBUG << "Entering state " << int (yystack_[0].state) << '\n';
It should be:
YYCDEBUG << "Entering state " << static_cast<int> (yystack_[0].state) << '\n';

Line 1437 does not use static_cast:
*yycdebug_ << ' ' << int (i->state);
It should be:
*yycdebug_ << ' ' << static_cast<int> (i->state);

**Comment by akimd** [comment]
Fix in https://lists.gnu.org/r/bison-patches/2020-01/msg00025.html.  Thanks!
