### ISSUE TITLE
Where is the INSTALL file?

### ISSUE THREAD

**Issue by yixuan0719** [akimd/bison#32]
Hello,
I want to exec the cross-compilation from tarball, but i cannot find the "INSTALL" file? How i should do?

**Comment by akimd** [comment]
Hi!
If you want to start from the git repo, you have to follow the procedure in `README.md`, which will build the `INSTALL` file.
Otherwise the easiest is to start from an actual tarball, available from https://ftp.gnu.org/gnu/bison/.  Cheers!
