### ISSUE TITLE
make: *** [Makefile:7745: src/bison-scan-code-c.o] Error 1

### ISSUE THREAD

**Issue by Hannah1746** [akimd/bison#47]
I am trying to install bison and when I run make I get this:
  GPERF    lib/iconv_open-aix.h
  GPERF    lib/iconv_open-hpux.h
  GPERF    lib/iconv_open-irix.h
  GPERF    lib/iconv_open-osf.h
  GPERF    lib/iconv_open-solaris.h
  GPERF    lib/iconv_open-zos.h
  GEN      lib/inttypes.h
  GEN      lib/textstyle.h
  GEN      lib/limits.h
  GEN      lib/locale.h
  GEN      lib/math.h
  GEN      lib/sched.h
  GEN      lib/signal.h
  GEN      lib/spawn.h
  GEN      lib/stdint.h
  GEN      lib/stdio.h
  GEN      lib/stdlib.h
  GEN      lib/string.h
  GEN      lib/sys/ioctl.h
  GEN      lib/sys/resource.h
  GEN      lib/sys/time.h
  GEN      lib/sys/times.h
  GEN      lib/sys/types.h
  GEN      lib/sys/wait.h
  GEN      lib/termios.h
  GEN      lib/time.h
  GEN      lib/unistd.h
  GEN      lib/unistr.h
  GEN      lib/unitypes.h
  GEN      lib/uniwidth.h
  GEN      lib/wchar.h
  GEN      lib/wctype.h
  LEX      src/scan-code.c
  LEX      src/scan-gram.c
  LEX      src/scan-skel.c
echo 3.7.1.23-6e1d8 > .version-t && mv .version-t .version
  CC       src/bison-AnnotationList.o
  CC       src/bison-InadequacyList.o
  CC       src/bison-Sbitset.o
  CC       src/bison-assoc.o
  CC       src/bison-closure.o
  CC       src/bison-complain.o
  CC       src/bison-conflicts.o
  CC       src/bison-counterexample.o
  CC       src/bison-derivation.o
  CC       src/bison-derives.o
  CC       src/bison-files.o
  CC       src/bison-fixits.o
  CC       src/bison-getargs.o
  CC       src/bison-glyphs.o
  CC       src/bison-gram.o
  CC       src/bison-graphviz.o
  CC       src/bison-ielr.o
  CC       src/bison-lalr.o
  CC       src/bison-location.o
  CC       src/bison-lr0.o
  CC       src/bison-lssi.o
  CC       src/bison-main.o
  CC       src/bison-muscle-tab.o
  CC       src/bison-named-ref.o
  CC       src/bison-nullable.o
  CC       src/bison-output.o
  CC       src/bison-parse-gram.o
  CC       src/bison-parse-simulation.o
  CC       src/bison-print-graph.o
  CC       src/bison-print-xml.o
  CC       src/bison-print.o
  CC       src/bison-reader.o
  CC       src/bison-reduce.o
  CC       src/bison-relation.o
  CC       src/bison-scan-code-c.o
src/scan-code-c.c:3:10: fatal error: src/scan-code.c: No such file or directory
 #include "src/scan-code.c"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:7745: src/bison-scan-code-c.o] Error 1

**Comment by akimd** [comment]
Hi!
This is weird, since "LEX src/scan-code.c" was run before.  Could you please run `make V=1`, so that we get more details?  And `ls src` in your build dir.
TIA!

**Comment by akimd** [comment]
Clang still finds issues in the code, see https://api.travis-ci.org/v3/job/724022874/log.txt for instance.

```
#                             -*- compilation -*-
231. conflicts.at:1096: testing Syntax error in consistent error state: glr2.cc ...
../../tests/conflicts.at:1096: COLUMNS=1000; export COLUMNS; NO_TERM_HYPERLINKS=1; export NO_TERM_HYPERLINKS;  bison --color=no -fno-caret -o input.cc input.y
../../tests/conflicts.at:1096: COLUMNS=1000; export COLUMNS; NO_TERM_HYPERLINKS=1; export NO_TERM_HYPERLINKS; VALGRIND_OPTS="$VALGRIND_OPTS --leak-check=summary --show-reachable=no"; export VALGRIND_OPTS;  bison --color=no -fno-caret -o input.cc input.y -Werror
stderr:
input.y:17.5-25: error: rule useless in parser due to conflicts [-Werror=other]
input.y:18.5-29: error: rule useless in parser due to conflicts [-Werror=other]
../../tests/conflicts.at:1096: sed 's,.*/$,,' stderr 1>&2
../../tests/conflicts.at:1096: COLUMNS=1000; export COLUMNS; NO_TERM_HYPERLINKS=1; export NO_TERM_HYPERLINKS; VALGRIND_OPTS="$VALGRIND_OPTS --leak-check=summary --show-reachable=no"; export VALGRIND_OPTS;  bison --color=no -fno-caret -o input.cc input.y --warnings=error
../../tests/conflicts.at:1096: COLUMNS=1000; export COLUMNS; NO_TERM_HYPERLINKS=1; export NO_TERM_HYPERLINKS; VALGRIND_OPTS="$VALGRIND_OPTS --leak-check=summary --show-reachable=no"; export VALGRIND_OPTS;  bison --color=no -fno-caret -o input.cc input.y -Wnone,none -Werror --trace=none
../../tests/conflicts.at:1096: COLUMNS=1000; export COLUMNS; NO_TERM_HYPERLINKS=1; export NO_TERM_HYPERLINKS; VALGRIND_OPTS="$VALGRIND_OPTS --leak-check=summary --show-reachable=no"; export VALGRIND_OPTS;  bison --color=no -fno-caret -o input.cc input.y --warnings=none -Werror --trace=none
../../tests/conflicts.at:1096: $CXX $CXXFLAGS $CPPFLAGS  $LDFLAGS -o input input.cc $LIBS
stderr:
input.cc:1448:3: error: definition of implicit copy constructor for 'yyGLRStackItem' is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated-copy-dtor]
  ~yyGLRStackItem() {
  ^
/usr/lib/llvm-10/bin/../include/c++/v1/memory:1876:31: note: in implicit copy constructor for 'yyGLRStackItem' first required here
            ::new((void*)__p) _Up(_VSTD::forward<_Args>(__args)...);
                              ^
/usr/lib/llvm-10/bin/../include/c++/v1/memory:1768:18: note: in instantiation of function template specialization 'std::__1::allocator<yyGLRStackItem>::construct<yyGLRStackItem, yyGLRStackItem>' requested here
            {__a.construct(__p, _VSTD::forward<_Args>(__args)...);}
                 ^
/usr/lib/llvm-10/bin/../include/c++/v1/memory:1595:14: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<yyGLRStackItem> >::__construct<yyGLRStackItem, yyGLRStackItem>' requested here
            {__construct(__has_construct<allocator_type, _Tp*, _Args...>(),
             ^
/usr/lib/llvm-10/bin/../include/c++/v1/memory:1724:15: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<yyGLRStackItem> >::construct<yyGLRStackItem, yyGLRStackItem>' requested here
              construct(__a, _VSTD::__to_address(__end2 - 1),
              ^
/usr/lib/llvm-10/bin/../include/c++/v1/vector:952:21: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<yyGLRStackItem> >::__construct_backward_with_exception_guarantees<yyGLRStackItem *>' requested here
    __alloc_traits::__construct_backward_with_exception_guarantees(
                    ^
/usr/lib/llvm-10/bin/../include/c++/v1/vector:1587:9: note: in instantiation of member function 'std::__1::vector<yyGLRStackItem, std::__1::allocator<yyGLRStackItem> >::__swap_out_circular_buffer' requested here
        __swap_out_circular_buffer(__v);
        ^
input.cc:1607:13: note: in instantiation of member function 'std::__1::vector<yyGLRStackItem, std::__1::allocator<yyGLRStackItem> >::reserve' requested here
    yyitems.reserve(yysize);
            ^
1 error generated.
stdout:
../../tests/conflicts.at:1096: exit code was 1, expected 0
231. conflicts.at:1096: 231. Syntax error in consistent error state: glr2.cc (conflicts.at:1096): FAILED (conflicts.at:1096)
```

Cheers!

**Comment by Hannah1746** [comment]
So if I run make V=1:
/bin/bash ./build-aux/ylwrap src/scan-code.l .c src/scan-code.c -- :  
/bin/bash ./build-aux/ylwrap src/scan-gram.l .c src/scan-gram.c -- :  
/bin/bash ./build-aux/ylwrap src/scan-skel.l .c src/scan-skel.c -- :  
/home/krablab/Documents/apps/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -DEXEEXT=\"\"   -I. -I./lib -I. -I./lib -DINSTALLDIR=\"/usr/local/bin\" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/krablab/Documents/apps/anaconda3/include -I/home/krablab/Documents/apps/anaconda3/include   -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/krablab/Documents/apps/anaconda3/include -MT src/bison-scan-code-c.o -MD -MP -MF src/.deps/bison-scan-code-c.Tpo -c -o src/bison-scan-code-c.o `test -f 'src/scan-code-c.c' || echo './'`src/scan-code-c.c
src/scan-code-c.c:3:10: fatal error: src/scan-code.c: No such file or directory
 #include "src/scan-code.c"
          ^~~~~~~~~~~~~~~~~
compilation terminated.

and when I run ls src:
AnnotationList.c          bison-print-xml.o  InadequacyList.c    reduce.c
AnnotationList.h          bison-reader.o     InadequacyList.h    reduce.h
assoc.c                   bison-reduce.o     lalr.c              relation.c
assoc.h                   bison-relation.o   lalr.h              relation.h
bison-AnnotationList.o    bison-Sbitset.o    local.mk            Sbitset.c
bison-assoc.o             closure.c          location.c          Sbitset.h
bison-closure.o           closure.h          location.h          scan-code-c.c
bison-complain.o          complain.c         lr0.c               scan-code.h
bison-conflicts.o         complain.h         lr0.h               scan-code.l
bison-counterexample.o    conflicts.c        lssi.c              scan-gram-c.c
bison-derivation.o        conflicts.h        lssi.h              scan-gram.h
bison-derives.o           counterexample.c   main.c              scan-gram.l
bison-files.o             counterexample.h   muscle-tab.c        scan-skel-c.c
bison-fixits.o            derivation.c       muscle-tab.h        scan-skel.h
bison-getargs.o           derivation.h       named-ref.c         scan-skel.l
bison-glyphs.o            derives.c          named-ref.h         state.c
bison-gram.o              derives.h          nullable.c          state.h
bison-graphviz.o          files.c            nullable.h          state-item.c
bison-ielr.o              files.h            output.c            state-item.h
bison-InadequacyList.o    fixits.c           output.h            symlist.c
bison-lalr.o              fixits.h           parse-gram.c        symlist.h
bison-location.o          flex-scanner.h     parse-gram.h        symtab.c
bison-lr0.o               getargs.c          parse-gram.y        symtab.h
bison-lssi.o              getargs.h          parse-simulation.c  system.h
bison-main.o              glyphs.c           parse-simulation.h  tables.c
bison-muscle-tab.o        glyphs.h           print.c             tables.h
bison-named-ref.o         gram.c             print-graph.c       uniqstr.c
bison-nullable.o          gram.h             print-graph.h       uniqstr.h
bison-output.o            graphviz.c         print.h             yacc
bison-parse-gram.o        graphviz.h         print-xml.c         yacc.in
bison-parse-simulation.o  i18n-strings.c     print-xml.h
bison-print-graph.o       ielr.c             reader.c
bison-print.o             ielr.h             reader.h

**Comment by akimd** [comment]
Your problem is:
```
/bin/bash ./build-aux/ylwrap src/scan-code.l .c src/scan-code.c -- :  
/bin/bash ./build-aux/ylwrap src/scan-gram.l .c src/scan-gram.c -- :  
/bin/bash ./build-aux/ylwrap src/scan-skel.l .c src/scan-skel.c -- :  
```

On my machine, I have:

```
/bin/sh /Users/akim/src/gnu/bison/build-aux/ylwrap /Users/akim/src/gnu/bison/src/scan-gram.l lex.yy.c src/scan-gram.c -- flex  
```

So I guess configure did not find flex. Flex is not needed when you start from a tarball, but it is required if you start from git.  Install it flex, and reconfigure.

Cheers!

**Comment by Hannah1746** [comment]
Worked great. Thank you!!
