### ISSUE TITLE
lalr1.cc and increased usage of noexcept

### ISSUE THREAD

**Issue by donmac703** [akimd/bison#63]
lalr1.cc contains the following code fragment:
------
class context
{
public:
    context (const ]b4_parser_class[& yyparser, const symbol_type& yyla);
      const symbol_type& lookahead () const { return yyla_; }
      symbol_kind_type token () const { return yyla_.kind (); }]b4_locations_if([[
      const location_type& location () const { return yyla_.location; }
-----
lookahead(), token(), and location() should be tagged with YY_NOEXCEPT.

Note that kind() is already tagged with YY_NOEXCEPT as shown below.
-----
/// The symbol kind (corresponding to \a state).
/// \a ]b4_symbol(-2, kind)[ when empty.
symbol_kind_type kind () const YY_NOEXCEPT;
-------

**Comment by akimd** [comment]
Fixed in master.
