### ISSUE TITLE
c++.m4 and increased usage of noexcept

### ISSUE THREAD

**Issue by donmac703** [akimd/bison#64]
c++.m4 contains the following code fragments

/// Destroy contents, and record that is empty. (around line 341)
void clear ()

clear() should be tagged as YY_NOEXCEPT.

Each of the destroy calls in the switch are already marked YY_NOEXCEPT.

/// Record that this symbol is empty. (around line 424)
void clear ();

clear() should be tagged as YY_NOEXCEPT.

]b4_inline([$1])[void (around line 545)
]b4_parser_class[::by_kind::clear ()
{
  kind_ = ]b4_symbol(-2, kind)[;
}

clear() should be tagged as YY_NOEXCEPT to match declaration.

**Comment by akimd** [comment]
Fixed in master.
