### ISSUE TITLE
make   error  

### ISSUE THREAD

**Issue by resplendent-star** [akimd/bison#65]
src/scan-code-c.c:3:10: fatal error: src/scan-code.c: No such file or directory
 #include "src/scan-code.c"src/scan-code-c.c:3:10: fatal error: src/scan-code.c: No such file or directory
 #include "src/scan-code.c"

**Comment by akimd** [comment]
Hi,
Sorry I had not seen your report earlier.  Did you manage to get Bison compile?  Please read carefully README-hacking.

**Comment by akimd** [comment]
@resplendent-star Ping.

**Comment by akimd** [comment]
No answer.

**Comment by vkottler** [comment]
I get errors no matter how I try to build:

```
$ make
...
  CC       src/bison-scan-code-c.o
src/scan-code-c.c:3:10: fatal error: src/scan-code.c: No such file or directory
    3 | #include "src/scan-code.c"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:9211: src/bison-scan-code-c.o] Error 1
make[2]: Leaving directory '/home/vkottler/third-party/bison'
make[1]: *** [Makefile:10351: all-recursive] Error 1
make[1]: Leaving directory '/home/vkottler/third-party/bison'
make: *** [Makefile:3857: all] Error 2
```

This is after following all of the canonical steps, and I've tried on the most recent 4 or 5 tagged release hashes.

**Comment by vkottler** [comment]
It's not getting generated at any point in the build, and I'm not finding any target in the `Makefile` hierarchy, or `./bootstrap`, or `./configure` that seems to manage building it or even being aware of it.
