### ISSUE TITLE
Usage of HAVE_UNISTD_H should be consistent

### ISSUE THREAD

**Issue by donmac703** [akimd/bison#70]
HAVE_UNISTD_H is found in various files as a guard against including unistd.h.

functions.m4
headers.m4
specific.m4

all contain #ifdef HAVE_UNISTD_H.

However, 

src/files.c
src/system.h

do not.

The usage of HAVE_UNISTD_H should be consistent across the codebase.

**Comment by akimd** [comment]
Hi,

Are you referring to`functions.m4`, `headers.m4` and `specific.m4` from submodules/autoconf?  We don't use these files, they are irrelevant to Bison (we use some files from Autoconf, but not these).

We should not be using `HAVE_UNISTD_H`, so AFAICT, Bison is fine as is.
