### ISSUE TITLE
Update the bison package on Cygwin to latest

### ISSUE THREAD

**Issue by XsongyangX** [akimd/bison#77]
The latest bison package on Cygwin is 3.0.4, but this repo is already at 3.6. Can you upload the most recent version on Cygwin? :)

**Comment by zmajeed** [comment]
Cygwin packages are updated by maintainers - cygwin says to ask for an update on the cygwin mailing list - https://cygwin.com/faq/faq.html#faq.using.old-packages

no question bison needs to be updated in cygwin - the current version is 3.0.4 from 2015 - https://cygwin.com/pipermail/cygwin/2015-January/219335.html

**Comment by XsongyangX** [comment]
Thanks for the info!

**Comment by akimd** [comment]
It seems I can close this issue :)

Cheers!
