### ISSUE TITLE
Link broken on README's "Build from tarball"

### ISSUE THREAD

**Issue by XsongyangX** [akimd/bison#78]
The link to the "INSTALL FILE" is broken. This is on the README.md.

**Comment by zmajeed** [comment]
INSTALL has been missing for years - I too looked for it recently when I tried building from the tarfile - I also noticed the tarfile on the releases page in this repo cannot be used to build - it's simply a tarfile of the repo and does not have a configure script

I had to get the bison 3.7.6 tarfile from the bison-announce mailing list - https://lists.gnu.org/archive/html/bison-announce/2021-03/msg00000.html

**Comment by zmajeed** [comment]
Also related the repo itself is actually missing some non-critical files - e.g. the C++ calc++ example has no grammar files - probably due to bad .gitignore entries

https://github.com/akimd/bison/tree/master/examples/c%2B%2B/calc%2B%2B

**Comment by akimd** [comment]
Hi,
No, the file is not missing, it's just not part of the git repository.  It will installed during the bootstrap process.

The README file is written to be read from the tarball.  People starting from the repo are expected to read README-hacking.

The example files are not to be found in the repo either, they are extracted by the build system when you run "make check".

Cheers!
