### ISSUE TITLE
--file-prefix in the docs

### ISSUE THREAD

**Issue by bitPogo** [akimd/bison#82]
Hello,
First of all thank you for maintaining this lovely Project!
However I found a small nitpick in the docs. The [paragraph about invocation of Bison](https://inst.eecs.berkeley.edu/~cs164/sp05/docs/jbison/bison.html#Invocation) uses the for `--file-prefix=prefix` the description of `--verbose`´, while in the [Declaration Summary](https://inst.eecs.berkeley.edu/~cs164/sp05/docs/jbison/bison.html#Decl%20Summary) it is correct.
Before I forget about it again, I thought I let you know.

**Comment by akimd** [comment]
Hi!

Thanks a lot for the bug report!  However, you are not pointing the documentation of the current version of Bison, and actually it's not even Bison (it's about "Bison and JBison").
The "official" documentation has it right: https://www.gnu.org/software/bison/manual/html_node/Output-Files.html

Cheers!
