### ISSUE TITLE
yynerrs unused-but-set-variable warning with Clang 15

### ISSUE THREAD

**Issue by nikic** [akimd/bison#89]
When building bison-generated parsers using Clang 15, a `-Wunused-but-set-variable` warning is thrown for the usually unused yynerrs variable:
```
/home/nikic/php/php-src-fast/Zend/zend_language_parser.c:4487:9: error: variable 'zendnerrs' set but not used [-Werror,-Wunused-but-set-variable]
    int yynerrs;
        ^
/home/nikic/php/php-src-fast/Zend/zend_language_parser.c:93:25: note: expanded from macro 'yynerrs'
#define yynerrs         zendnerrs
```
Probably the declaration needs to be annotated with YY_ATTRIBUTE_UNUSED.

**Comment by akimd** [comment]
Thanks for the report!

**Comment by cooljeanius** [comment]
> Thanks for the report!

@akimd any plans to include closing commit a166d54 in a release anytime soon? See further discussion in #103
